image: golang:1.12.7

variables:
  VERSION: "1.0"
  CI_REGISTRY: "docker.io"
  CI_REGISTRY_IMAGE: "docker.io/kj187/kubernetes-ingress-linklist"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
- test
- build
- docker

go:lint:
  stage: test
  script:
  - make lint

go:build:
  stage: build
  script:
  - mkdir bin
  - make go_build_linux
  artifacts:
    paths:
    - bin/kubernetes-ingress-linklist
  only:
  - master

docker:build:push:
  stage: docker
  services:
  - docker:dind
  image: docker:stable
  script:
  - docker build -t "${CI_REGISTRY_IMAGE}:${VERSION}.${CI_PIPELINE_ID}" .
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
  - docker push "${CI_REGISTRY_IMAGE}:${VERSION}.${CI_PIPELINE_ID}"
  - echo ${VERSION}.${CI_PIPELINE_ID} > VERSION
  - cat VERSION
  artifacts:
    paths:
    - VERSION
  dependencies:
  - go:build
  only:
  - master