apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-ingress-linklist.fullname" . }}
  labels:
    {{- include "k8s-ingress-linklist.labels" . | nindent 4 }}
data:
  settings.yaml: |
    redirectRootPageTo: /custom/global
    customPages:
      global:
        title: Global
        links:
        - title: kj187
          link: http://kj187.de