apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-ingress-linklist
  labels:
    app.kubernetes.io/name: k8s-ingress-linklist

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8s-ingress-linklist
  labels:
    app.kubernetes.io/name: k8s-ingress-linklist
rules:
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-ingress-linklist
  labels:
    app.kubernetes.io/name: k8s-ingress-linklist
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-ingress-linklist
subjects:
  - kind: ServiceAccount
    name: k8s-ingress-linklist
    namespace: default