apiVersion: v1
description: UI with a list of all available Kubernetes ingresses per namespace
name: kubernetes-ingress-linklist
version: 1.0.0
home: https://gitlab.com/kj187/kubernetes-ingress-linklist