# Default values for kubernetes-ingress-linklist
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kj187/kubernetes-ingress-linklist
  tag: "1.0.73818410"
  pullPolicy: IfNotPresent

service:
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

resources:
  limits:
    memory: 100Mi
  requests:
    memory: 50Mi
    cpu: 5m