name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    env:
      GO111: "on"
      CGO_ENABLED: 0   
      GOPATH: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:

    - name: Install Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      
    - name: Check out code
      uses: actions/checkout@v2

    - name: Go lint
      shell: bash
      run: |
        GO111MODULE=$GO111 go get -u golang.org/x/lint/golint
        golint -set_exit_status $(shell go list ./... | grep -v /vendor/)

    - name: Get dependencies   
      run: GO111MODULE=$GO111 go mod vendor

    - name: Build
      run: |
        mkdir bin
        GO111MODULE=$GO111 CGO_ENABLED=$CGO_ENABLED GOOS=linux GOARCH=amd64 go build -o bin/kubernetes-ingress-linklist -mod vendor cmd/kubernetes-ingress-linklist/main.go
        
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: kj187/kubernetes-ingress-linklist
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        tag_semver: true
        
